stages:
- deploy

deploy-cloud-function:
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo $GCP_ACCOUNT_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - rm gcloud-service-key.json
    - gcloud config set project cicd-practice-404800
    - gcloud functions deploy hello-world
      --runtime=python39 
      --entry-point=hello_world
      --region=europe-west1
      --source=.
      --trigger-http
  rules:
    - if: $CI_COMMIT_BRANCH == "main"